[workspace]
resolver = "2"

members = [
    "unidir_events",
]

[workspace.dependencies]
bevy = "0.15.0-rc.3"
codee = "0.2"
console_error_panic_hook = "0.1"
console_log = "1"
leptos = "0.7.0-rc1"
log = "0.4"
web-sys = "0.3"
wasm-bindgen = "0.2"
wasm-bindgen-test = "0.3.0"

[package]
name = "leptos-use-examples"
version = "0.3.3"
edition = "2021"
