[workspace]
resolver = "2"

members = [
    "unidir_events",
]

[workspace.dependencies]
bevy = { version = "0.15", default-features = false }
console_error_panic_hook = "0.1"
leptos = { version = "0.7.0", features = ["csr"] }
leptos-bevy-canvas = { path = "../../leptos-bevy-canvas" }
leptos-bevy-canvas-examples = { path = "." }
leptos-use = "0.15"
web-sys = "0.3"
wasm-bindgen = "0.2"
wasm-bindgen-test = "0.3.0"

[package]
name = "leptos-bevy-canvas-examples"
version = "0.3.3"
edition = "2021"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
